# Generated by Django 3.1.5 on 2021-01-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('small_desc', models.CharField(max_length=50)),
                ('big_desc', models.TextField()),
            ],
        ),
    ]
